language: node_js
compiler: default
matrix:
  exclude:
  # Disable the default build and use customized matrix only.
  - compiler: default
  include:
  # Node Stable (9.3)   Linux (Trusty)      G++6.3.0
  - os: linux
    dist: trusty
    node_js: '9.3'
    compiler: g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER_OVERRIDE="CXX=g++-6 CC=gcc-6"

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    ulimit -c unlimited
    export ${COMPILER_OVERRIDE}
  fi
install:
- npm install cmake-js -g
- npm install --no-fetch
script:
- npm test
- |
  if [ -f ./core ]; then
    gdb --batch --quite -ex "thread apply all bt full" -ex "quit" $(which node) ./core
  fi
- npm run unittest
