language: node_js
compiler: default
matrix:
  exclude:
  # Disable the default build and use customized matrix only.
  - compiler: default
  #
  # 2018-04-19 : There is a compability issue for the following platform/compiler/environment combination:
  #                - Ubuntu 14.04
  #                - GCC 5.x OR GCC 6.x
  #                - Node 8.10.0+ OR Node 9.3.0+
  #              This issue causes a crash on Napa.js.
  #              Issue detail: https://github.com/nodejs/node/issues/17817
  #
  #              Current available workaround:
  #                1: Use Node 8.9.1 or 9.2.1
  #                2: Use binaries (libnapa.so and napa-binding.node) that compiled in Ubuntu 16.04
  #                3: Use GCC 7.x+
  #
  #              Since travis-CI does not support Ubuntu 16.04 yet, we will use GCC 7.x+ for all linux
  #              build for now.
  #                                                                                        - fs-eire
  #
  include:
  # Node 6.x            Linux (Ubuntu Precise 12.04)     G++7.x
  - os: linux
    dist: precise
    node_js: '6'
    compiler: g++-5
    addons:
      apt:
        # The apt source 'ubuntu-toolchain-r-test' is for G++ 5.x
        # The apt source 'george-edison55-precise-backports' is for CMake 3.2+
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - g++-5
        - cmake-data
        - cmake
    env:
    - COMPILER_OVERRIDE="CXX=g++-5 CC=gcc-5"
  # Node 6.x            OS X (Yosemite)                  AppleClang 6.1
  - os: osx
    node_js: '6'
    osx_image: xcode6.4
  # Node LTS (8.x)      Linux (Ubuntu Trusty 14.04)      G++7.x
  - os: linux
    dist: trusty
    node_js: '8'
    compiler: g++-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - COMPILER_OVERRIDE="CXX=g++-7 CC=gcc-7"
  # Node LTS (8.x)      OS X (El Capitan)                AppleClang 7.3
  - os: osx
    node_js: '8'
    osx_image: xcode7.3
  # Node Stable (9.x)   Linux (Ubuntu Trusty 14.04)      G++7.x
  # 2018-04-19 : TODO - change to Ubuntu Xenial 16.04 once Travis CI supports.
  - os: linux
    dist: xenial
    node_js: '9'
    compiler: g++-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - COMPILER_OVERRIDE="CXX=g++-7 CC=gcc-7"
  # Node Stable (9.x)   macOS (Sierra)                   AppleClang 8.1
  - os: osx
    node_js: '9'
    osx_image: xcode8.3

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    sudo apt-get install -y gdb
    ulimit -c unlimited
    export ${COMPILER_OVERRIDE}
  fi
install:
- npm install cmake-js -g
- npm install --no-fetch
script:
- npm test
- |
  if [ -e ./core ]; then
    gdb --batch --quiet -ex "thread apply all bt full" -ex "quit" $(which node) ./core
  fi
- npm run unittest
