language: node_js
compiler: default
matrix:
  exclude:
  # Disable the default build and use customized matrix only.
  - compiler: default
  include:
  # Node Stable (9.3)   Linux (Trusty)      G++6.3.0
  - os: linux
    dist: trusty
    node_js: '9.3'
    compiler: g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER_OVERRIDE="CXX=g++-6 CC=gcc-6"
  # Node Stable (9.3)   Linux (Trusty)      G++6.3.0
  - os: linux
    dist: trusty
    node_js: '9.3'
    compiler: g++-5
    addons:
      apt:
        # The apt source 'ubuntu-toolchain-r-test' is for GCC 5+
        # The apt source 'george-edison55-precise-backports' is for CMake 3.2+
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - g++-5
        - cmake-data
        - cmake
    env:
    - COMPILER_OVERRIDE="CXX=g++-5 CC=gcc-5"
  - os: linux
    dist: trusty
    group: deprecated-2017Q4
    node_js: '9.3'
    compiler: g++-5
    addons:
      apt:
        # The apt source 'ubuntu-toolchain-r-test' is for GCC 5+
        # The apt source 'george-edison55-precise-backports' is for CMake 3.2+
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - g++-5
        - cmake-data
        - cmake
    env:
    - COMPILER_OVERRIDE="CXX=g++-5 CC=gcc-5"
  # Node Stable (9.3)   Linux (Trusty)      G++6.3.0
  - os: linux
    dist: trusty
    node_js: '9.2.1'
    compiler: g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER_OVERRIDE="CXX=g++-6 CC=gcc-6"

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    sudo apt-get install -y gdb  
    ulimit -c unlimited
    export ${COMPILER_OVERRIDE}
  fi
install:
- npm install cmake-js -g
- npm install --no-fetch --debug
script:
- node -e "require('.').zone.create('zone4');"
- npm run unittest
- ls
- ls -a
- find ./ -name "core"
- |
  if [ -e ./core ]; then
    gdb --batch --quiet -ex "thread apply all bt full" -ex "quit" $(which node) ./core
  fi
- |
  if [ -e ./lib/core ]; then
    gdb --batch --quiet -ex "thread apply all bt full" -ex "quit" $(which node) ./lib/core
  fi
